apiVersion: v1
kind: Plugin
metadata:
  author: luorisky
  name: EmailAlarmListenerPlugin
  repository: ''
  version: 2.0.0
  description:
    en_US: SMTP email alarm listener plugin that sends notifications to QQ groups
    zh_Hans: SMTP邮件告警监听插件，自动发送通知到QQ群
  label:
    en_US: Email Alarm Listener
    zh_Hans: 邮件告警监听插件
  icon: assets/icon.svg
spec:
  config:
  - name: default_group_id
    label:
      en_US: Default QQ Group ID
      zh_Hans: 默认QQ群号
    type: string
    default: "123456789"
    description:
      en_US: The default QQ group ID to send email alarm notifications to
      zh_Hans: 发送邮件告警通知的默认QQ群号
  dependencies: []
  components:
    EventListener:
      fromDirs:
      - path: components/event_listener/
    Command:
      fromDirs:
      - path: components/commands/
execution:
  python:
    path: main.py
    attr: EmailAlarmListenerPlugin
