# Auto generated by LangBot Plugin SDK.
# Please refer to https://docs.langbot.app/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

from langbot_plugin.api.definition.components.common.event_listener import EventListener
from langbot_plugin.api.entities import events, context
import logging

# 设置日志
logger = logging.getLogger(__name__)


class DefaultEventListener(EventListener):

    async def initialize(self):
        await super().initialize()

        # 监听私聊消息
        @self.handler(events.PersonMessageReceived)
        async def handle_person_message(event_context: context.EventContext):
            """处理私聊消息事件"""
            print("="*50)
            print("🔍 收到私聊消息事件:")
            print(f"事件类型: {type(event_context.event).__name__}")
            print(f"事件内容: {event_context.event}")
            print(f"发送者ID: {event_context.event.sender_id}")
            print(f"消息内容: {event_context.event.message_chain}")
            print("="*50)

        # 监听群消息
        @self.handler(events.GroupMessageReceived)
        async def handle_group_message(event_context: context.EventContext):
            """处理群消息事件"""
            print("="*50)
            print("🔍 收到群消息事件:")
            print(f"事件类型: {type(event_context.event).__name__}")
            print(f"事件内容: {event_context.event}")
            print("="*50)

        logger.info("EventListener 初始化完成，开始监听事件...")