# Auto generated by LangBot Plugin SDK.
# Please refer to https://docs.langbot.app/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

from typing import Any, AsyncGenerator

from langbot_plugin.api.definition.components.command.command import Command, Subcommand
from langbot_plugin.api.entities.builtin.command.context import ExecuteContext, CommandReturn


class SnmpStatus(Command):

    async def initialize(self):
        await super().initialize()

        @self.subcommand(
            name="",  # 空字符串表示根命令
            help="Show SNMP Trap plugin status",
            usage="snmp_status",
            aliases=["status"],
        )
        async def show_status(self, context: ExecuteContext) -> AsyncGenerator[CommandReturn, None]:
            print(f"🚀 收到命令: {context.command_text}")

            # 最简单的测试消息
            simple_text = "Hello from SNMP Trap Plugin! Command received."
            print(f"📤 返回简单消息: {simple_text}")

            yield CommandReturn(text=simple_text)
            print(f"✅ 消息已返回")